Building scraming link detecting system
reactxsw/Smilewinbot pull request #7
Opened 2021-12-28 06:03 UTC by DeepKungChannel

2021-12-28 06:12 UTC, reactxsw requested changes
ไปเอาใส่ไว้ใน on_message ใน level.py เลย ถ้าลิงค์เปน virus = ไม่ได้เลเวล ถ้ามันมี on_message 2 ตัวตัวเเรกจะไม่ติด เเล้วจะติดเเค่ ตัวหลังเรียงตาม A- Z s อยู่หลัง l เพราะงั้น ระบบ เลเลวจะไม่ติด

- bypass bitly

2021-12-28 06:16 UTC, reactxsw commented
ใช้ aiohttp เเทน requests จะได้เปน asyncio เเล้วเปลี่ยน .content เปน .text เลยจะได้ไม่ต้อง decode utf-8

2021-12-28 06:17 UTC, DeepKungChannel commented
Ok ครับ

2021-12-29 05:29 UTC, reactxsw approved these changes

2021-12-29 05:29 UTC, merged